### PR TITLE
Migrated to Aurelia latest 1.0.x using Monterey.

### PR DESCRIPTION
**Pull request by AlainBaslter**
Current with this release http://blog.aurelia.io/2016/09/07/patch-releases-9-7-2016-2/

Tested each control & related capabilities manually and filled spreadsheet attached.

Methodology:

[Aurelia Syncfusion Bridge Tests.zip](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/files/463121/Aurelia.Syncfusion.Bridge.Tests.zip)
- Used Monterey with 2 projects: aurelia-syncfusion-bridge & samples.
- Updated Aurelia versions using Monterey NPM & JSPM package update capabilities.
- Added missing gulp-util in package.json manually.
- Ran gulp watch
- Tested using Chrome on Windows 7 64 bit

### CODE REVIEW

**Comment by JeroenVinke** [comment]
@AlainBaslter Thanks! this is released as 0.2.2

**Comment by adriatic** [comment]
@JeroenVinke 

### I hope that you preserved the log of this work for my collection of Monterey marketing data

**Comment by JeroenVinke** [comment]
@adriatic all we need is in [this issue](https://github.com/aurelia-ui-toolkits/aurelia-syncfusion-bridge/issues/40). I didn't do any work here, @AlainBaslter did :smile:

**Comment by adriatic** [comment]
Thanks for this reference. @AlainBaslter - would you care to be a "visiting blogger" for our http://blog.aureliatools.com site describing this work with the focus on Monterey?

**Comment by AlainBaslter** [comment]
@adriatic sure I'd be glad to help promote Monterey it helped me a lot.
But you know what the next logical step is now that aurelia-syncfusion-bridge is current!
**Bundling!**
I see there is a new project started under the aurelia-ui-toolkits umbrella that precisely that.
Its a good idea for that would speed up load times with the opportunity to weed out some of the controls not used, especially the complex ones with lots of code like the ejSpreadsheet. Some of these I have no need for.

**Pull request merged**
