### PR TITLE
two-way binding on editor elements enable

### PR DESCRIPTION
**Pull request by irsali**
Two way data-binding on controls that uses hidden element like dropdown, dateTimePicker was not working.

### CODE REVIEW

**Comment by irsali** [comment]
i was trying two-way data-binding on dropdown control but could not get it running correctly. The problem is simple that dropdown value changed is not reflected back on model. 

```
<input class="form-control"
                   ej-drop-down-list="e-value.two-way:contact.city;e-data-source.bind:cities;e-fields.bind:fields;e-watermark-text.bind:watermarkText;"
                    />
```

I have investigated deep down and found below issue cause.

First in widget.base.js -> createWidget : !this.isEditor, it should be this.isEditor
```
if (!this.ejOptions && !this.isEditor) {
      this.createTwoWays();
    }
```

**Comment by karthickthangasamy** [comment]
@irsali The two-way binding was achieved through `_change` handler instead of `createTwoWays()` method specifically for **_editor_** components. Two-way property not working in `ejDropDownList` was an issue with that component. We have fixed this issue, which will be available in our next release of [syncfusion-javascript](https://www.npmjs.com/package/syncfusion-javascript) package.


We fixed the issue and attached `ej.dropdown.min.js` in the below link. 

[ej.dropdown.min.js](http://www.syncfusion.com/downloads/support/directtrac/184762/ze/ej.dropdownlist.min.js-1420245854.zip)

If you are installing `syncfusion-javascript` via `JSPM`, then replace the attached `ej.dropdown.min.js` file in `jspm_packages\npm\syncfusion-javascript@15.3.26\Scripts\ej\web `

If you are installing `syncfusion-javascript` via `NPM`, then replace the attached `ej.dropdown.min.js` file in `node_modules\syncfusion-javascript\Scripts\ej\web`

**Comment by irsali** [comment]
@karthickthangasamy 
Thanks for your efforts, I thought createTwoWays() registers model.value for two way binding but it was not being called. then i made above change, the strange thing is that i got two way binding work as expected after my change.

However you are an expert here, I will replace ej.dropdown.min.js and test. Thank you again.

**Comment by irsali** [comment]
@karthickthangasamy 
I have tested your ej.dropdown.min.js made it working. However, other controls like datepicker, timepicker needs same correction. Do, i need to raise issue or you will resolve them too before next release.

**Comment by karthickthangasamy** [comment]
@irsali Those components are working fine in two-way binding. Could you please check the below sample for `ejDatePicker`. In which, we displayed the `selectedDate` in span upon changing the date.

http://aureliajq.syncfusion.com/#/samples/datepicker/Display-Inline

**Comment by irsali** [comment]
@karthickthangasamy  Thank you.

**Comment by karthickthangasamy** [comment]
Welcome 😄 @irsali

**Pull request closed without merging**
